### ISSUE TITLE
Why compile GCC, etc. from source in `Dockerfile` for the container?

### ISSUE THREAD

**Issue by DavidCodingLounge** [blahgeek/emacs-appimage#3]
I am very new to building AppImages, so please pardon me if my questions are silly. I am running this locally (to build some older versions of Emacs) using the `local_run.sh` script; I was wondering why do we need to build so many dependencies from source in the `Dockerfile`? For example, we are building GCC from source which takes almost an entire day (seriously) to compile from source.

Why can't we just use the pre-made binary via `apt` for these dependencies to make spinning up the Docker container faster? Does the pre-made binary not have the right compilation flags set and for the AppImage we need a different compiler? That would seem strange, to me at least. Are certain versions of the dependencies (e.g. GCC, BinUtils, TreeSitter, MPS, etc.) incompatible with building Emacs?

I am very curious to learn more and understand the decisions. Great work and I really do love the quality of this repository (it definitely helped me understand some of the finer points about building Emacs).

**Comment by blahgeek** [comment]
Hello,

Yeah no those are good questions.

In order to make the result AppImage compatible with as many distributions as possible, we should choose an old distribution as the build environment, in this case, Ubuntu 18.04 (in docker). This is because that we do not bundle all dynamic libraries into the AppImage for various reasons (e.g. we would use libc.so in the system, other appimage tools do this too, [this link](https://github.com/AppImageCommunity/pkg2appimage/blob/master/excludelist) provides more infos), so using an older distribution means linking to older libraries which means usually means compatibility with newer distributions.

So, for those libraries that are not provided in Ubuntu 18.04 repo, we need to build it. For example, a newer version of libgccjit than the one from the ubuntu repo is [required by emacs](https://lists.gnu.org/archive/html/help-gnu-emacs/2022-01/msg00151.html) for native-comp, so we need to build gcc for it. Others like treesitter or mps are simply not provided by ubuntu 18.04 repo. As for binutils, as far as I remembered, the ones in the system is not compatible with gcc-13 so we need to build a newer version.  Also, since we need to build them anyway, I would generally prefer newer versions for better performance and features.

If you are asking why building in the dockerfile instead of the run.sh, it's for making use of the docker layer cache.
